- name: K8s | Include saved vars from the control plane node
  include_vars:
    dir: "{{ inventory_dir }}/host_vars/"

- name: K8s | Insert custom DNS entry to join to the control plane
  lineinfile:
    line: "{{ control_plane_ip }} {{ cluster_endpoint }}""
    path: "/etc/hosts"
    state: present

- name: K8s | Join the node to the cluster
  command: "{{ kubeadm_join_command }}"